### ISSUE TITLE
Fatal error: String index is out of bounds occurs in getXY(code:)

### ISSUE THREAD

**Issue by hisaboh** [nekowen/GeoHex3.swift#1]
A code `let _ = GeoHex3.getZone(code: "Bc")` crashed with "Fatal error: String index is out of bounds".

**Comment by nekowen** [comment]
Thanks for the bug report!
Now that the problem has been reproduced, I'll fix it 👍

**Comment by nekowen** [comment]
Fixed in v0.2.0
